app = "living-room-bot"
kill_signal = "SIGINT"
kill_timeout = 5

[processes]
bot = "python -m living_room_bot.main"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["paketo-buildpacks/python"]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
